name: persistent_bottom_nav_bar_example_project
description: An example project for persistent_bottom_nav_bar

version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  persistent_bottom_nav_bar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
